In [161]:
import numpy as np
global C
def embarca(A,inicio,fin):
    global C
    tam=fin-inicio    
    if tam==1:
        C[inicio,fin]=A[inicio,fin]
        return C[inicio][fin]
    if C[inicio][fin]==-1:
        actual=A[inicio,fin]
        for i in range(inicio+1,fin,1):
            val=embarca(A,inicio,i)+embarca(A,i,fin)
            if val<actual:
                actual=val
        C[inicio][fin]=actual
    return C[inicio,fin]

def main(A,tam):
    global C
    C=np.ones((tam,tam))*-1
    embarca(A,0,tam-1)
    print(C)

In [162]:
A=np.matrix([[0,1,5,10,15],[-1,0,2,4,20],[-1,-1,0,3,30],[-1,-1,-1,0,5],[-1,-1,-1,-1,0]])
print (A)
main(A,5)

[[ 0  1  5 10 15]
 [-1  0  2  4 20]
 [-1 -1  0  3 30]
 [-1 -1 -1  0  5]
 [-1 -1 -1 -1  0]]
[[ -1.   1.   3.   5.  10.]
 [ -1.  -1.   2.   4.   9.]
 [ -1.  -1.  -1.   3.   8.]
 [ -1.  -1.  -1.  -1.   5.]
 [ -1.  -1.  -1.  -1.  -1.]]
